"""initial schema

Revision ID: 0e3ddc745ade
Revises: 
Create Date: 2026-09-10 15:19:35.744564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e3ddc745ade'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('check_date', sa.String(length=10), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'check_date', name='uq_attendance_day')
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendances_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_user_id'), ['user_id'], unique=False)

    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('catalog_key', sa.String(length=40), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupons_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupons_is_used'), ['is_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupons_user_id'), ['user_id'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('start_price', sa.Integer(), nullable=False),
    sa.Column('buy_now_price', sa.Integer(), nullable=True),
    sa.Column('current_price', sa.Integer(), nullable=False),
    sa.Column('auction_type', sa.String(length=10), server_default='general', nullable=False),
    sa.Column('blind_price_rule', sa.String(length=10), server_default='first', nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('final_price', sa.Integer(), nullable=True),
    sa.Column('extended_count', sa.Integer(), nullable=False),
    sa.Column('spotlight_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_auction_type'), ['auction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_winner_id'), ['winner_id'], unique=False)

    op.create_table('mission_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mission_key', sa.String(length=40), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mission_key', name='uq_mission_claim')
    )
    with op.batch_alter_table('mission_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mission_claims_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mission_claims_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('related_type', sa.String(length=30), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('point_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_point_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_transactions_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('yes_odds', sa.Float(), nullable=False),
    sa.Column('no_odds', sa.Float(), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_status'), ['status'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)

    op.create_table('skill_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('start_price', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('provide_type', sa.String(length=50), nullable=True),
    sa.Column('available_schedule', sa.Text(), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_items_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_items_status'), ['status'], unique=False)

    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('bidder_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['bidder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bids_bidder_id'), ['bidder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bids_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bids_item_id'), ['item_id'], unique=False)

    op.create_table('blind_bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('bidder_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['bidder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blind_bids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blind_bids_bidder_id'), ['bidder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blind_bids_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blind_bids_item_id'), ['item_id'], unique=False)

    op.create_table('prediction_bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('payout', sa.Integer(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction_bets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_bets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_bets_prediction_id'), ['prediction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_bets_user_id'), ['user_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('skill_item_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['skill_item_id'], ['skill_items.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_skill_item_id'), ['skill_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_target_user_id'), ['target_user_id'], unique=False)

    op.create_table('skill_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_item_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['skill_item_id'], ['skill_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_bookings_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_bookings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_bookings_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_bookings_skill_item_id'), ['skill_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_bookings_status'), ['status'], unique=False)

    op.create_table('escrows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('payer_id', sa.Integer(), nullable=False),
    sa.Column('payee_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['skill_bookings.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escrows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escrows_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_escrows_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_escrows_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_escrows_payee_id'), ['payee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_escrows_payer_id'), ['payer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_escrows_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escrows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escrows_status'))
        batch_op.drop_index(batch_op.f('ix_escrows_payer_id'))
        batch_op.drop_index(batch_op.f('ix_escrows_payee_id'))
        batch_op.drop_index(batch_op.f('ix_escrows_item_id'))
        batch_op.drop_index(batch_op.f('ix_escrows_id'))
        batch_op.drop_index(batch_op.f('ix_escrows_booking_id'))

    op.drop_table('escrows')
    with op.batch_alter_table('skill_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_skill_bookings_skill_item_id'))
        batch_op.drop_index(batch_op.f('ix_skill_bookings_seller_id'))
        batch_op.drop_index(batch_op.f('ix_skill_bookings_id'))
        batch_op.drop_index(batch_op.f('ix_skill_bookings_buyer_id'))

    op.drop_table('skill_bookings')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_skill_item_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_item_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_author_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('prediction_bets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_bets_user_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_bets_prediction_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_bets_id'))

    op.drop_table('prediction_bets')
    with op.batch_alter_table('blind_bids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blind_bids_item_id'))
        batch_op.drop_index(batch_op.f('ix_blind_bids_id'))
        batch_op.drop_index(batch_op.f('ix_blind_bids_bidder_id'))

    op.drop_table('blind_bids')
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bids_item_id'))
        batch_op.drop_index(batch_op.f('ix_bids_id'))
        batch_op.drop_index(batch_op.f('ix_bids_bidder_id'))

    op.drop_table('bids')
    with op.batch_alter_table('skill_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_items_status'))
        batch_op.drop_index(batch_op.f('ix_skill_items_seller_id'))
        batch_op.drop_index(batch_op.f('ix_skill_items_id'))
        batch_op.drop_index(batch_op.f('ix_skill_items_category'))

    op.drop_table('skill_items')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_reports_id'))

    op.drop_table('reports')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_status'))
        batch_op.drop_index(batch_op.f('ix_predictions_id'))

    op.drop_table('predictions')
    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_point_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_point_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_point_transactions_id'))

    op.drop_table('point_transactions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('mission_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mission_claims_user_id'))
        batch_op.drop_index(batch_op.f('ix_mission_claims_id'))

    op.drop_table('mission_claims')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_winner_id'))
        batch_op.drop_index(batch_op.f('ix_items_status'))
        batch_op.drop_index(batch_op.f('ix_items_seller_id'))
        batch_op.drop_index(batch_op.f('ix_items_id'))
        batch_op.drop_index(batch_op.f('ix_items_category'))
        batch_op.drop_index(batch_op.f('ix_items_auction_type'))

    op.drop_table('items')
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupons_user_id'))
        batch_op.drop_index(batch_op.f('ix_coupons_is_used'))
        batch_op.drop_index(batch_op.f('ix_coupons_id'))

    op.drop_table('coupons')
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendances_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_id'))

    op.drop_table('attendances')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
