"""add composite index on point_transactions for user/type/created_at

Revision ID: 706e7a038649
Revises: 0e3ddc745ade
Create Date: 2026-09-21 16:59:22.630988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '706e7a038649'
down_revision: Union[str, Sequence[str], None] = '0e3ddc745ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_point_tx_user_type_created', ['user_id', 'type', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_point_tx_user_type_created')

    # ### end Alembic commands ###
